import { NextResponse } from 'next/server';
import pool from '@/lib/db';

export async function POST(request: Request) {
    try {
        // 1. Verify Environment Variables
        const token = process.env.GITHUB_TOKEN;
        const username = process.env.GITHUB_USERNAME;

        if (!token || !username) {
            return NextResponse.json(
                { error: 'Missing GITHUB_TOKEN or GITHUB_USERNAME in environment variables.' },
                { status: 500 }
            );
        }

        // 2. Fetch Data from DB
        const profileRes = await pool.query('SELECT * FROM portfolio.profile LIMIT 1');
        const profile = profileRes.rows[0];

        // Fetch Projects
        const projectsRes = await pool.query('SELECT title, description, tech, link FROM portfolio.projects ORDER BY id DESC LIMIT 4');
        const projects = projectsRes.rows;

        // Fetch Blogs
        const blogsRes = await pool.query('SELECT id, title, excerpt FROM portfolio.blogs WHERE is_hidden = false ORDER BY date DESC LIMIT 4');
        const blogs = blogsRes.rows;

        // 3. Generate Markdown Content
        // Use safe defaults if fields are missing
        const name = profile?.name || username;
        const role = profile?.role || 'Developer';
        const summary = profile?.summary || 'Welcome to my profile!';
        const location = profile?.location || 'Earth';

        // Fix [object Object]: Parse currently_learning correctly
        let learningTopic = 'New Tech';
        try {
            const learningData = typeof profile?.currently_learning === 'string'
                ? JSON.parse(profile.currently_learning)
                : profile?.currently_learning;

            if (Array.isArray(learningData) && learningData.length > 0) {
                learningTopic = learningData[0].topic || 'New Tech';
            } else if (typeof learningData === 'object' && learningData?.topic) {
                learningTopic = learningData.topic;
            }
        } catch (e) {
            learningTopic = 'New Tech';
        }

        // Sanitize username (alphanumeric and hyphens only, rigid clean)
        const safeUsername = username.replace(/[^a-zA-Z0-9-]/g, '');

        // Construct the liquid header URL (dynamic)
        const headerUrl = `https://capsule-render.vercel.app/api?type=waving&color=gradient&height=300&section=header&text=${encodeURIComponent(name)}&fontSize=90&animation=fadeIn&fontAlignY=38&desc=${encodeURIComponent(role)}&descAlignY=51&descAlign=62`;

        const readmeContent = `<!--
  AUTO-GENERATED BY PORTFOLIO APP
  Last Updated: ${new Date().toISOString()}
-->

<div align="center">
  <img src="${headerUrl}" width="100%"/>
</div>

<div align="center">
  
  [![Portfolio](https://img.shields.io/badge/✨_View_My_Interactive_Portfolio-7025F5?style=for-the-badge&logo=googlechrome&logoColor=white)](https://www.jumaan.me)
  
  ${profile?.linkedin ? `<a href="${profile.linkedin}"><img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" /></a>` : ''}
  ${profile?.email ? `<a href="mailto:${profile.email}"><img src="https://img.shields.io/badge/Email-D14836?style=for-the-badge&logo=gmail&logoColor=white" /></a>` : ''}
  ${profile?.twitter ? `<a href="${profile.twitter}"><img src="https://img.shields.io/badge/X-000000?style=for-the-badge&logo=x&logoColor=white" /></a>` : ''}

</div>

<br />

### 👨‍💻 About Me

- 🔭 I’m currently working as a **${role}**
- 🌱 I’m currently exploring **${learningTopic}**
- 🏙️ Based in **${location}**
- 📄 ${summary}

<br />

### 🛠️ Tech Stack

<div align="center">
    <!-- Dynamic Skills: Using a static list for now, ideally strictly mapped from DB skills -->
    <img src="https://skillicons.dev/icons?i=java,spring,hibernate,mysql,postgres,docker,react,nextjs,ts,tailwind,git,linux&perline=6" />
</div>

<br />

### 🚀 Featured Projects

${projects.map((p: any) => {
            // Parse tech if string
            let techStack = [];
            try { techStack = typeof p.tech === 'string' ? JSON.parse(p.tech) : p.tech || []; } catch (e) { }
            const techString = techStack.slice(0, 5).join(' • ');

            return `- **[${p.title}](${p.link || '#'})**: ${p.description} <br/> _Stack:_ \`${techString}\``;
        }).join('\n')}

<br />

### ✍️ Latest Articles

${blogs && blogs.length > 0 ? blogs.map((b: any) => {
            // Strip HTML from excerpt if present
            const cleanExcerpt = b.excerpt ? b.excerpt.replace(/<[^>]*>?/gm, "") : "";
            // Truncate if too long
            const shortExcerpt = cleanExcerpt.length > 100 ? cleanExcerpt.substring(0, 100) + '...' : cleanExcerpt;

            return `- **[${b.title}](https://www.jumaan.me/blogs/${b.id})**: ${shortExcerpt}`;
        }).join('\n') : '_No articles yet._'}



### 📈 GitHub Stats

<div align="center">
  <img src="https://github-readme-stats-fast.vercel.app/api?username=${safeUsername}&show_icons=true&theme=radical&hide_border=true&hide_title=true" height="180" alt="${safeUsername}'s GitHub Stats" />
</div>

<br />

<div align="center">
  <h3>✍️ Read My Blogs</h3>
  <p>I write about technology, coding, and my journey.</p>
  <a href="https://www.jumaan.me/blogs">
    <img src="https://img.shields.io/badge/📖_Read_My_Blogs_on_Jumaan.me-7025F5?style=for-the-badge&logo=hashnode&logoColor=white" alt="Read My Blogs" />
  </a>
</div>

<br />

<div align="center">
  <i>"The only way to do great work is to love what you do."</i>
  <br/>
  — <b>Steve Jobs</b>
</div>
`;

        // 4. GitHub API Logic
        const repo = username; // Profile repo is same as username
        const path = 'README.md';
        const apiUrl = `https://api.github.com/repos/${username}/${repo}/contents/${path}`;

        // A. Get current SHA (if exists)
        let sha;
        const getRes = await fetch(apiUrl, {
            headers: {
                'Authorization': `Bearer ${token}`,
                'Accept': 'application/vnd.github.v3+json',
                'User-Agent': 'Portfolio-App'
            }
        });

        if (getRes.ok) {
            const data = await getRes.json();
            sha = data.sha;
        } else if (getRes.status !== 404) {
            // Error other than "Not Found"
            const errText = await getRes.text();
            console.error('GitHub Get Error:', errText);
            // We'll proceed without SHA, assuming it might be a new file or we'll get 409 conflict
            // But 404 is the only "safe" error.
        }

        // B. Create/Update File
        const putRes = await fetch(apiUrl, {
            method: 'PUT',
            headers: {
                'Authorization': `Bearer ${token}`,
                'Accept': 'application/vnd.github.v3+json',
                'User-Agent': 'Portfolio-App'
            },
            body: JSON.stringify({
                message: 'chore: update profile readme via portfolio app',
                content: Buffer.from(readmeContent).toString('base64'),
                sha: sha // Include SHA if we found one
            })
        });

        if (!putRes.ok) {
            const errText = await putRes.text();
            return NextResponse.json({ error: `GitHub API Error: ${errText}` }, { status: putRes.status });
        }

        return NextResponse.json({ success: true, message: 'README updated successfully!' });

    } catch (error: any) {
        console.error('Sync Error:', error);
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
    }
}
