ALTER TABLE request_audit.sessions
ADD COLUMN IF NOT EXISTS browser_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS operating_system VARCHAR(100),
ADD COLUMN IF NOT EXISTS device_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS country_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS city_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS user_name VARCHAR(150),
ADD COLUMN IF NOT EXISTS user_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS user_phone VARCHAR(50);
